version: '3.4'
services:
  outloud.quiz.service:
    image: outloud.quiz.service
    build:
      context: ..
      dockerfile: Outloud.QuizService/Dockerfile
    environment:
      ASPNETCORE_URLS: 'http://+:5002'
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'
    ports:
      - 5002:5002

  outloud.quiz.service.tests:
    image: outloud.quiz.service.tests
    build:
      context: ..
      dockerfile: Outloud.QuizService/Dockerfile
      target: test
    environment:
      ASPNETCORE_URLS: 'http://+:5002'
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'

  outloud.log.service:
    image: outloud.log.service
    build:
      context: ..
      dockerfile: Outloud.LogService/Dockerfile
    environment:
      ASPNETCORE_URLS: 'http://+:5003'
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'
    ports:
      - 5003:5003
      
  outloud.log.service.tests:
    image: outloud.log.service.tests
    build:
      context: ..
      dockerfile: Outloud.LogService/Dockerfile
      target: test
    environment:
      ASPNETCORE_URLS: 'http://+:5003'
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'