version: '3.4'
services:
  outloud.quiz.service:
    image: outloud/outloud.quiz.service
    environment:
      ASPNETCORE_URLS: 'http://+:5002'
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'
    ports:
      - 5002:5002