version: '3.4'
services:
outloud.api:
    image: outloud/outloud.api
    environment:
      ASPNETCORE_URLS: 'http://+:5000'
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'
    ports:
      - 5000:5000

  outloud.quiz.service:
    image: outloud/outloud.quiz.service
    environment:
      ASPNETCORE_URLS: 'http://+:5002'
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'
    ports:
      - 5002:5002