version: '3.4'
services:
  outloud.quiz.service:
    build:
      context: ..
      dockerfile: Outloud.QuizService/Dockerfile
    restart: on-failure
    environment:
      ASPNETCORE_URLS: 'https://+:5000'
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'
    ports:
      - 5000:5000
  outloud.quiz.service.tests:
    build:
      context: ..
      dockerfile: Outloud.QuizService/Dockerfile
      target: test
    restart: on-failure
    environment:
      ASPNETCORE_URLS: 'https://+:5000'
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'