version: '3.4'
services:
  outloud.api:
    image: outloud.api
    build:
      context: ..
      dockerfile: Outloud.Api/Dockerfile
    environment:
      ASPNETCORE_URLS: 'http://+:5000'
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'
    ports:
      - 5002:5002

  outloud.api.tests:
    image: outloud.api.tests
    build:
      context: ..
      dockerfile: Outloud.Api/Dockerfile
      target: test
    environment:
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'

  outloud.quiz.service:
    image: outloud.quiz.service
    build:
      context: ..
      dockerfile: Outloud.QuizService/Dockerfile
    environment:
      ASPNETCORE_URLS: 'http://+:5002'
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'
    ports:
      - 5002:5002

  outloud.quiz.service.tests:
    image: outloud.quiz.service.tests
    build:
      context: ..
      dockerfile: Outloud.QuizService/Dockerfile
      target: test
    environment:
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'

  outloud.score.service:
    image: outloud.score.service
    build:
      context: ..
      dockerfile: Outloud.ScoreService/Dockerfile
    environment:
      ASPNETCORE_URLS: 'http://+:5003'
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'
    ports:
      - 5003:5003

  outloud.score.service.tests:
    image: outloud.score.service.tests
    build:
      context: ..
      dockerfile: Outloud.ScoreService/Dockerfile
      target: test
    environment:
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'
      
  outloud.common:
    image: outloud.common
    build:
      context: ..
      dockerfile: Outloud.Common/Dockerfile
      args:
        version: ${NUGET_VERSION}
        apikey: ${NUGET_API_KEY}
    ports:
      - '5003:5003'

  outloud.common.tests:
    image: outloud.common.tests
    build:
      context: ..
      dockerfile: Outloud.Common/Dockerfile
      args:
        version: ${NUGET_VERSION}
        apikey: ${NUGET_API_KEY}
      target: test
    environment:
      WAIT_HOSTS: ''
      WAIT_HOSTS_TIMEOUT: '60'